const mongoose = require("mongoose")

const CustomerSchema = mongoose.Schema({
    CustomerTypeId:{
        type:String
    },
    CustomerId:{
        type:String
    },
    CustomerName:{
        type:String
    },
    HeadOfficeAddress:{
        type:String,   
    },
    HeadOfficeDistrict:{
        type:String,  
    },
    HeadOfficeProvince:{
        type:String
    },
    HeadOfficeCountry:{
        type:String
    },
    HeadOfficeStateId:{
        type:Number

    },
    HeadOfficeCityId:{
        type:String
    },
    HeadOfficePin:{
        type:String
    },
    SiteAddress:{
        type:String
    },
    SiteDistrict:{
        type:String
    },
   SiteAddressProvince:{
      type:String
    },
    SiteAddressCountry:{
        type:String
    },
    SiteAddressStateId:{
        type:Number

    },
    SiteAddressCityId:{
        type:String

    },
    SiteAddressPin:{
        type:String
    },
    ContactPersonName:{
        type:String
    },
    Designation:{
        type:String
    },
    Email:{
        type:String
    },
    ContactNo:{
        type:String
    },
    LandlineNo:{
        type:String
    },
    CompanyRegistrationNo:{
        type:String
    },
    CompanyVATNo:{
        type:String
    },
    CustomerCategoryId:{
        type:String
    },
    CustomerStatus:{
        type:String
    },
    CustomerRegionId:{
        type:String
    },
    locationId:{
        type:String
    },
    CustomerIndustryId:{
        type:String
    },
    EquipmentId:{
        type:String
    },
    TypeOfEquipmentId:{
        type:String
    },
    MakeOfBoiler:{
        type:String
    },
    CapacityId:{
        type:String
    },
    MainSteamPressureId:{
        type:String
    },
    TypeOfFuelFired:{
        type:String
    },
    MainSteamTemperatureId:{
       type:String
    },
    YearOfInstallation:{
        type:String
    },
    NoOfInstallation:{
        type:String
    },
    BoilerMakeNo:{
        type:String
    },
    PollutionControlEquipmentId:{
        type:String
    },
    MakeOfPollutionControlEquipMent:{
        type:String
    },
    Province:{
        type:String
    }

    
},{
timestamps:true
})
module.exports = mongoose.model("Customer",CustomerSchema)