const mongoose = require("mongoose")

const CustomerSchema = mongoose.Schema({
    CustomerType:{
        type:String
    },
    CustomerId:{
        type:String
    },
    CustomerName:{
        type:String
    },
    HeadOfficeAddress:{
        type:String,   
    },
    HeadOfficeDistrict:{
        type:String,  
    },
    HeadOfficeProvince:{
        type:String
    },
    HeadOfficeCountry:{
        type:String
    },
    HeadOfficeStateId:{
        type:Number

    },
    HeadOfficeCityId:{
        type:String
    },
    HeadOfficePin:{
        type:String
    },
    SiteAddress:{
        type:String
    },
    SiteDistrict:{
        type:String
    },
   SiteAddressProvince:{
      type:String
    },
    SiteAddressCountry:{
        type:String
    },
    SiteAddressStateId:{
        type:Number

    },
    SiteAddressCityId:{
        type:String

    },
    SiteAddressPin:{
        type:String
    },
    ContactPersonName:{
        type:String
    },
    Designation:{
        type:String
    },
    Email:{
        type:String
    },
    ContactNo:{
        type:String
    },
    LandlineNo:{
        type:String
    },
    CompanyRegistrationNo:{
        type:String
    },
    CompanyVATNo:{
        type:String
    },
    CustomerCategory:{
        type:String
    },
    CustomerStatus:{
        type:String
    },
    Region:{
        type:String
    },
    Location:{
        type:String
    },
    Industry:{
        type:String
    },
    Equipment:{
        type:String
    },
    TypeOfEquipment:{
        type:String
    },
    MakeOfBoiler:{
        type:String
    },
    CapacityUnit:{
        type:String
    },
    MainSteamPressure:{
        type:String
    },
    TypeOfFuelFired:{
        type:String
    },
    MainSteamTemperature:{
       type:String
    },
    YearOfInstallation:{
        type:String
    },
    NoOfInstallation:{
        type:String
    },
    BoilerMakeNo:{
        type:String
    },
    PollutionControlEquipMent:{
        type:String
    },
    MakeOfPollutionControlEquipMent:{
        type:String
    }
    
},{
timestamps:true
})
module.exports = mongoose.model("Customer",CustomerSchema)