const mongoose = require("mongoose")

const SalesEnquirySchema = mongoose.Schema({
    SalesEnquiryId:{
        type:String
    },
    Email:{
type:String
    },
    Password:{
        type:String   
    },
    EnquiryDate:{
        type:String
    },
    CustomerId:{
        type:String
    },
    RFQNo:{
        type:String, 
    },
    EnquiryOwnerId:{
        type:String
    },
    OfferingTypeId:{
        type:String
    },
    EquipmentId:{
        type:String
    },
    TypeOfEquipmentId:{
        type:String
    },
    EnquiryTypeId:{
        type:String
    },
    ItemDetails:{
        type:String
    },
    Description:{
        type:String
    } ,
    GroupId:{
        type:String,
    },
    Unit:{
        type:String
    },
    Quantity:{
        type:String
    },
    WeightedsalesId:{
        type:String
    },
    RequiredDate:{
        type:String
    },
    EnquiryStatusId:{
        type:String
    },
    Remarks:{
        type:String
    },
    AdditionalComments:{
        type:String
    },
    TargetDate:{
        type:String
    },
    verificationCode:{
        type:Number
    },
    InstallationTypeId:{
        type:String
    }
},{
timestamps:true
})
module.exports = mongoose.model("SalesEnquiry",SalesEnquirySchema)