const mongoose = require("mongoose")

const SuplierSchema = mongoose.Schema({
    SuplierType:{
        type:String
    },
    SuplierId:{
        type:String
    },
    SuplierName:{
        type:String
    },
   RegisteredOfficeAddress:{
        type:String,   
    },
   RegisteredOfficeDistrict:{
        type:String,  
    },
   RegisteredOfficeProvince:{
        type:String
    },
   RegisteredOfficeCountry:{
        type:String
    },
    RegisteredOfficeStateId:{
        type:Number
    },
    RegisteredOfficeCityId:{
        type:String
    },
   RegisteredOfficePin:{
        type:String
    },
    BillingAddress:{
        type:String
    },
    BillingDistrict:{
        type:String
    },
   BillingAddressProvince:{
      type:String
    },
    BillingAddressCountry:{
        type:String
    },
    BillingAddressStateId:{
        type:Number
    },
    BillingAddressCityId:{
        type:String
    },
    BillingAddressPin:{
        type:String
    },
    ContactPersonName:{
        type:String
    },
    Designation:{
        type:String
    },
    Email:{
        type:String
    },
    ContactNo:{
        type:String
    },
    CountryCode:{
        type:String
    },
    LegelStructure:{
        type:String
    },
    DateOfCompanyEstablish:{
        type:String
    },
    TypeOfBussiness:{
        type:String
    },
    GeograpicServiceArea:{
        type:String
    },
    BankName:{
        type:String
    },
    BankBranch:{
        type:String
    },
    BankBranchCode:{
        type:String
    },
    IFSCCode:{
        type:String
    },
    BankManagerName:{
        type:String
    },
    ContactNo:{
        type:String
    },
    BankBranchAccountManagerName:{
        type:String
    },
    BankAddress:{
        type:String
    },
    BankEmailId:{
        type:String
    }, 
},{
timestamps:true
})
module.exports = mongoose.model("Suplier",SuplierSchema)