const express = require("express")
const {CreateAllocatecostestimationtopurchaseteamDetails,viewAllocatecostestimationtopurchaseteamDetails,deleteAllocatecostestimationtopurchaseteamDetails,updateAllocatecostestimationtopurchaseteamDetails} = require("../controller/Allocatecostestimationtopurchaseteam_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Allocatecostestimationtopurchaseteam:
 *       type: object
 *       required:
 *         - AllocatecostestimationtopurchaseteamId
 *         - AllocationId
 *         - Date
 *         - Remark
 *       properties:
 *         AllocatecostestimationtopurchaseteamId:
 *           type: integer
 *           description: AllocatecostestimationtopurchaseteamId
 *         AllocationId:
 *           type: string
 *           description: AllocationId
 *         Date:
 *           type: string
 *           description: AllocatecostestimationtopurchaseteamId
 *         Remark:
 *           type: string
 *           description: Remark
 *       example:
 *         AllocatecostestimationtopurchaseteamId: autoGenerated
 *         AllocationId: ED101
 *         Date: 08-12-2023       
 *         Remark: Allocate succesffully       
 *
 */

/**
 * @swagger
 * /api/v1/viewAllocatecostestimationtopurchaseteamDetails:
 *   get:
 *     summary: get all Allocatecostestimationtopurchaseteam
 *     tags: [Allocatecostestimationtopurchaseteam]
 *     responses:
 *       200:
 *         description: get All Allocatecostestimationtopurchaseteam
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Allocatecostestimationtopurchaseteam'
 */
router.route("/viewAllocatecostestimationtopurchaseteamDetails").get(viewAllocatecostestimationtopurchaseteamDetails)


/**
 * @swagger
 * /api/v1/CreateAllocatecostestimationtopurchaseteamDetails:
 *   post:
 *     summary: add a new Allocatecostestimationtopurchaseteam
 *     tags: [Allocatecostestimationtopurchaseteam]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Allocatecostestimationtopurchaseteam'
 *     responses:
 *       200:
 *         description: create Allocatecostestimationtopurchaseteam successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Allocatecostestimationtopurchaseteam'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateAllocatecostestimationtopurchaseteamDetails").post(CreateAllocatecostestimationtopurchaseteamDetails)

/**
 * @swagger
 * /api/v1/deleteAllocatecostestimationtopurchaseteamDetails/{AllocatecostestimationtopurchaseteamId}:
 *   delete:
 *     summary: Delete a Allocatecostestimationtopurchaseteam
 *     tags: [Allocatecostestimationtopurchaseteam]
 *     parameters:
 *         - in: path
 *           name: AllocatecostestimationtopurchaseteamId
 *           required: true
 *           description: AllocatecostestimationtopurchaseteamId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Allocatecostestimationtopurchaseteam deleted successfully
 *       404:
 *         description: Allocatecostestimationtopurchaseteam not found
 */

router.route("/deleteAllocatecostestimationtopurchaseteamDetails/:AllocatecostestimationtopurchaseteamId").delete(deleteAllocatecostestimationtopurchaseteamDetails)

/**
* @swagger
* /api/v1/updateAllocatecostestimationtopurchaseteamDetails:
*   post:
*     summary: upPassword Allocatecostestimationtopurchaseteam Details
*     tags: [Allocatecostestimationtopurchaseteam]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/Allocatecostestimationtopurchaseteam'
*     responses:
*       200:
*         description: update Allocatecostestimationtopurchaseteam Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/Allocatecostestimationtopurchaseteam'
*       500:
*         description: Some server error
*/
router.route("/updateAllocatecostestimationtopurchaseteamDetails").post(updateAllocatecostestimationtopurchaseteamDetails)
module.exports = router

