const express = require("express")
const {CreateDepartMentDetails,viewDepartMentDetails,deleteDepartMentDetails,updateDepartMentDetails,getSingleDepartMentDetails} = require("../controller/DepartMent_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     DepartMent:
 *       type: object
 *       required:
 *         - DepartMentId
 *         - DepartMentName
 *         - Status
 *       properties:
 *         DepartMentId:
 *           type: integer
 *           description: DepartMentId
 *         DepartMentName:
 *           type: string
 *           description: DepartMentName
 *         Status:
 *           type: string
 *           description: DepartMentId
 *       example:
 *         DepartMentId: autoGenerated
 *         DepartMentName: DepartMent
 *         Status: Active       
 *
 */

/**
 * @swagger
 * /api/v1/viewDepartMentDetails:
 *   get:
 *     summary: get all DepartMent
 *     tags: [DepartMent]
 *     responses:
 *       200:
 *         description: get All DepartMent
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/DepartMent'
 */
router.route("/viewDepartMentDetails").get(viewDepartMentDetails)


/**
 * @swagger
 * /api/v1/CreateDepartMentDetails:
 *   post:
 *     summary: add a new DepartMent
 *     tags: [DepartMent]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/DepartMent'
 *     responses:
 *       200:
 *         description: create DepartMent successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/DepartMent'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateDepartMentDetails").post(CreateDepartMentDetails)

  /**
 * @swagger
 * /api/v1/deleteDepartMentDetails/{DepartMentId}:
 *   delete:
 *     summary: Delete an DepartMent
 *     tags: [DepartMent]
 *     parameters:
 *         - in: path
 *           DepartMentName: DepartMentId
 *           required: true
 *           description: DepartMentId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: DepartMent delete successfully
 *   
 */
router.route("/deleteDepartMentDetails/:DepartMentId").delete(deleteDepartMentDetails)

/**
* @swagger
* /api/v1/updateDepartMentDetails:
*   post:
*     summary: upPassword DepartMent Details
*     tags: [DepartMent]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/DepartMent'
*     responses:
*       200:
*         description: update DepartMent Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/DepartMent'
*       500:
*         description: Some server error
*/
router.route("/updateDepartMentDetails").post(updateDepartMentDetails)
/**
 * @swagger
 * /api/v1/getSingleDepartMentDetails/{DepartMentId}:
 *   get:
 *     summary: Get a DepartMent by ID
 *     tags: [DepartMent]
 *     description: Retrieve a DepartMent by their unique ID.
 *     parameters:
 *       - in: path
 *         name: DepartMentId
 *         required: true
 *         description: ID of the DepartMent to retrieve
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Successfully retrieved the DepartMent
 *       404:
 *         description: DepartMent not found
 */
router.route("/getSingleDepartMentDetails/:DepartMentId").get(getSingleDepartMentDetails)
module.exports = router

