const express = require("express")
const {CreateGroupDetails,viewGroupDetails,deleteGroupDetails,updateGroupDetails} = require("../controller/group_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Group:
 *       type: object
 *       required:
 *         - GroupId
 *         - GroupName
 *         - Status
 *       properties:
 *         GroupId:
 *           type: integer
 *           description: GroupId
 *         GroupName:
 *           type: string
 *           description: GroupName
 *         Status:
 *           type: string
 *           description: GroupId
 *       example:
 *         GroupId: autoGenerated
 *         GroupName: SalesEnquiry
 *         Status: Active       
 *
 */

/**
 * @swagger
 * /api/v1/viewGroupDetails:
 *   get:
 *     summary: get all Group
 *     tags: [Group]
 *     responses:
 *       200:
 *         description: get All Group
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Group'
 */
router.route("/viewGroupDetails").get(viewGroupDetails)


/**
 * @swagger
 * /api/v1/CreateGroupDetails:
 *   post:
 *     summary: add a new Group
 *     tags: [Group]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Group'
 *     responses:
 *       200:
 *         description: create Group successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Group'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateGroupDetails").post(CreateGroupDetails)

/**
 * @swagger
 * /api/v1/deleteGroupDetails/{GroupId}:
 *   delete:
 *     summary: Delete a Group
 *     tags: [Group]
 *     parameters:
 *         - in: path
 *           name: GroupId
 *           required: true
 *           description: GroupId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Group deleted successfully
 *       404:
 *         description: Group not found
 */

router.route("/deleteGroupDetails/:GroupId").delete(deleteGroupDetails)

/**
* @swagger
* /api/v1/updateGroupDetails:
*   post:
*     summary: upPassword Group Details
*     tags: [Group]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/Group'
*     responses:
*       200:
*         description: update Group Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/Group'
*       500:
*         description: Some server error
*/
router.route("/updateGroupDetails").post(updateGroupDetails)
module.exports = router

