const express = require("express")
const {CreateProjectDetails,viewProjectDetails,deleteProjectDetails,updateProjectDetails,getSingleProjectDetails} = require("../controller/Project_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Project:
 *       type: object
 *       required:
 *         - ProjectId
 *         - ProjectName
 *         - ProjectTypeId
 *         - CustomerId
 *         - ProjectStatus
 *         - EstimatedAmt
 *         - StartDate
 *         - EndDate
 *         - Rating
 *         - EnquiryOwnerId
 *       properties:
 *         ProjectId:
 *           type: integer
 *           description: ProjectId
 *         ProjectName:
 *           type: string
 *           description: ProjectName
 *         CustomerId:
 *           type: string
 *           description: CustomerId
 *         ProjectTypeId:
 *           type: string
 *           description: ProjectTypeId
 *         ProjectStatus:
 *           type: string
 *           description: ProjectId
 *         EstimatedAmt:
 *           type: string
 *           description: ProjectId
 *         StartDate:
 *           type: string
 *           description: Province
 *         EndDate:
 *           type: string
 *           description: EndDate
 *         Rating:
 *           type: string
 *           description: EndDate
 *         EnquiryOwnerId:
 *           type: string
 *           description: EndDate
 *       example:
 *         ProjectId: autoGenerated
 *         ProjectName: ArrowEnegry
 *         ProjectTypeId: 1
 *         CustomerId: CD1010002,
 *         ProjectStatus: open
 *         EstimatedAmt: 162023
 *         StartDate: 04-07-2023
 *         EndDate: 01-09-2023
 *         Rating: 1
 *         EnquiryOwnerId: ED102
 *         
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewProjectDetails:
 *   get:
 *     summary: get all Project
 *     tags: [Project]
 *     responses:
 *       200:
 *         description: get All Project
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Project'
 */
router.route("/viewProjectDetails").get(viewProjectDetails)


/**
 * @swagger
 * /api/v1/CreateProjectDetails:
 *   post:
 *     summary: Add a new Project
 *     tags: [Project]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Project'
 *     responses:
 *       '200':
 *         description: Project created successfully
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Project'
 *       '500':
 *         description: Server error
 */

 router.route("/CreateProjectDetails").post(CreateProjectDetails)

 /**
* @swagger
* /api/v1/deleteProjectDetails/{ProjectId}:
*   delete:
*     summary: Delete a Project
*     tags: [Project]
*     parameters:
*         - in: path
*           name: ProjectId
*           required: true
*           description: The ID of the project to delete
*           schema:
*              type: string
*     responses:
*       204:
*         description: Project deleted successfully
*       401:
*         description: Unauthorized - User not authenticated
*       404:
*         description: Project not found
*/

router.route("/deleteProjectDetails/:ProjectId").delete(deleteProjectDetails)

/**
* @swagger
* /api/v1/updateProjectDetails:
*   post:
*     summary: Update Company Project Details
*     tags: [Project]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/Project'
*     responses:
*       200:
*         description: Update Company Project Details successfully
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/Project'
*       500:
*         description: Some server error
*/

router.route("/updateProjectDetails").post(updateProjectDetails)
/**
 * @swagger
 * /api/v1/getSingleProjectDetails/{ProjectId}:
 *   get:
 *     summary: Get a Project by ID
 *     tags: [Project]
 *     description: Retrieve a Project by their unique ID.
 *     parameters:
 *       - in: path
 *         name: ProjectId
 *         required: true
 *         description: ID of the Project to retrieve
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Successfully retrieved the Project
 *       404:
 *         description: Project not found
 */
router.route("/getSingleProjectDetails/:ProjectId").get(getSingleProjectDetails)
module.exports = router

