const express = require("express")
const {CreatePurchaseEstimationEnquiryDetails,viewPurchaseEstimationEnquiryDetails,deletePurchaseEstimationEnquiryDetails,updatePurchaseEstimationEnquiryDetails,getSinglePurchaseEstimationEnquiryDetails} = require("../controller/PurchaseEstimationEnquiry_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     PurchaseEstimationEnquiry:
 *       type: object
 *       required:
 *         - PurchaseEstimationEnquiryId
 *         - SalesEnquiryId
 *         - EnquiryDate
 *         - CustomerId
 *         - EnquiryOwner
 *         - OfferingType
 *         - EnquiryType
 *         - Equipment
 *         - TypeofEquipment
 *         - EnquiryDescription
 *         - EnquiryStatus
 *         - Remark
 *         - AddtionalComments
 *         - TargetDate
 *       properties:
 *         PurchaseEstimationEnquiryId:
 *           type: integer
 *           description: PurchaseEstimationEnquiryId
 *         SalesEnquiryId:
 *           type: string
 *           description: SalesEnquiryId
 *         CustomerId:
 *           type: string
 *           description: CustomerId
 *         EnquiryDate:
 *           type: string
 *           description: PurchaseEstimationEnquiryId
 *         EnquiryOwner:
 *           type: string
 *           description: PurchaseEstimationEnquiryId
 *         OfferingType:
 *           type: string
 *           description: PurchaseEstimationEnquiryId
 *         EnquiryType:
 *           type: string
 *           description: EnquiryType
 *         Equipment:
 *           type: string
 *           description: Equipment
 *         TypeofEquipment:
 *           type: string
 *           description: Equipment
 *         EnquiryDescription:
 *           type: string
 *           description: Equipment
 *         EnquiryStatus:
 *           type: string
 *           description: Equipment
 *         Remark:
 *           type: string
 *           description: Remark
 *         AddtionalComments:
 *           type: string
 *           description: AddtionalComments
 *         TargetDate:
 *           type: string
 *           description: AddtionalComments
 *       example:
 *         PurchaseEstimationEnquiryId: autoGenerated
 *         SalesEnquiryId: PurchaseEstimationEnquiry
 *         EnquiryDate: PurchaseEstimationEnquiry@example.com
 *         CustomerId: PurchaseEstimationEnquiry@123
 *         EnquiryOwner: CS-IT
 *         OfferingType: India
 *         EnquiryType: 01-03-2023
 *         Equipment: InActive
 *         TypeofEquipment: Active
 *         EnquiryDescription: Active
 *         EnquiryStatus: Active
 *         Remark: Active
 *         AddtionalComments: Active
 *         TargetDate: Active
 *         
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewPurchaseEstimationEnquiryDetails:
 *   get:
 *     summary: get all PurchaseEstimationEnquiry
 *     tags: [PurchaseEstimationEnquiry]
 *     responses:
 *       200:
 *         description: get All PurchaseEstimationEnquiry
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/PurchaseEstimationEnquiry'
 */
router.route("/viewPurchaseEstimationEnquiryDetails").get(viewPurchaseEstimationEnquiryDetails)


/**
 * @swagger
 * /api/v1/CreatePurchaseEstimationEnquiryDetails:
 *   post:
 *     summary: add a new PurchaseEstimationEnquiry
 *     tags: [PurchaseEstimationEnquiry]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/PurchaseEstimationEnquiry'
 *     responses:
 *       200:
 *         description: create PurchaseEstimationEnquiry successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/PurchaseEstimationEnquiry'
 *       500:
 *         description: Some server error
 */
 router.route("/CreatePurchaseEstimationEnquiryDetails").post(CreatePurchaseEstimationEnquiryDetails)

  /**
 * @swagger
 * /api/v1/deletePurchaseEstimationEnquiryDetails/{PurchaseEstimationEnquiryId}:
 *   delete:
 *     summary: Delete an PurchaseEstimationEnquiry
 *     tags: [PurchaseEstimationEnquiry]
 *     parameters:
 *         - in: path
 *           SalesEnquiryId: PurchaseEstimationEnquiryId
 *           required: true
 *           description: PurchaseEstimationEnquiryId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: PurchaseEstimationEnquiry delete successfully
 *   
 */
router.route("/deletePurchaseEstimationEnquiryDetails/:PurchaseEstimationEnquiryId").delete(deletePurchaseEstimationEnquiryDetails)

/**
* @swagger
* /api/v1/updatePurchaseEstimationEnquiryDetails:
*   post:
*     summary: upCustomerId PurchaseEstimationEnquiry Details
*     tags: [PurchaseEstimationEnquiry]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/PurchaseEstimationEnquiry'
*     responses:
*       200:
*         description: update PurchaseEstimationEnquiry Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/PurchaseEstimationEnquiry'
*       500:
*         description: Some server error
*/
router.route("/updatePurchaseEstimationEnquiryDetails").post(updatePurchaseEstimationEnquiryDetails)

// swagger.js
/**
 * @swagger
 * components:
 *   schemas:
 *     PurchaseEnquiry:
 *       type: object
 *       properties:
 *         id:
 *           type: string
 *     PurchaseEnquiryResponse:
 *       type: object
 *       properties:
 *         result:
 *           type: string
 *         details:
 *           type: string
 */

/**
 * @swagger
 * /api/v1/getSinglePurchaseEstimationEnquiryDetails:
 *   post:
 *     summary: Get purchase enquiry estimation by ID
 *     tags: [PurchaseEstimationEnquiry]
 *     description: Retrieve purchase enquiry estimation based on an ID passed in the request body.
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/PurchaseEnquiry'
 *     responses:
 *       200:
 *         description: Purchase enquiry estimation
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/PurchaseEnquiryResponse'
 *       404:
 *         description: Purchase enquiry not found
 */
router.route("/getSinglePurchaseEstimationEnquiryDetails").post(getSinglePurchaseEstimationEnquiryDetails)

module.exports = router

