const express = require("express")
const {CreatePurchaseOrderDetails,viewPurchaseOrderDetails,deletePurchaseOrderDetails,updatePurchaseOrderDetails} = require("../controller/PurchaseOrder_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     PurchaseOrder:
 *       type: object
 *       required:
 *         - PurchaseOrderId
 *         - Reference
 *         - CreatedBy
 *         - ConfirmationDate
 *         - Vendor
 *         - ReceiptDate
 *         - PurchaseRepresentative
 *         - Total
 *         - CreatedDate
 *       properties:
 *         PurchaseOrderId:
 *           type: integer
 *           description: PurchaseOrderId
 *         Reference:
 *           type: string
 *           description: Reference
 *         ConfirmationDate:
 *           type: string
 *           description: ConfirmationDate
 *         CreatedBy:
 *           type: string
 *           description: PurchaseOrderId
 *         Vendor:
 *           type: string
 *           description: PurchaseOrderId
 *         ReceiptDate:
 *           type: string
 *           description: PurchaseOrderId
 *         PurchaseRepresentative:
 *           type: string
 *           description: PurchaseRepresentative
 *         Total:
 *           type: string
 *           description: Total
 *         CreatedDate:
 *           type: string
 *           description: Total
 *       example:
 *         PurchaseOrderId: autoGenerated
 *         Reference: PurchaseOrder
 *         CreatedBy: PurchaseOrder@example.com
 *         ConfirmationDate: PurchaseOrder@123
 *         Vendor: CS-IT
 *         ReceiptDate: India
 *         PurchaseRepresentative: 01-03-2023
 *         Total: InActive
 *         CreatedDate: Active
 *         
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewPurchaseOrderDetails:
 *   get:
 *     summary: get all PurchaseOrder
 *     tags: [PurchaseOrder]
 *     responses:
 *       200:
 *         description: get All PurchaseOrder
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/PurchaseOrder'
 */
router.route("/viewPurchaseOrderDetails").get(viewPurchaseOrderDetails)


/**
 * @swagger
 * /api/v1/CreatePurchaseOrderDetails:
 *   post:
 *     summary: add a new PurchaseOrder
 *     tags: [PurchaseOrder]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/PurchaseOrder'
 *     responses:
 *       200:
 *         description: create PurchaseOrder successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/PurchaseOrder'
 *       500:
 *         description: Some server error
 */
 router.route("/CreatePurchaseOrderDetails").post(CreatePurchaseOrderDetails)

  /**
 * @swagger
 * /api/v1/deletePurchaseOrderDetails/{PurchaseOrderId}:
 *   delete:
 *     summary: Delete an PurchaseOrder
 *     tags: [PurchaseOrder]
 *     parameters:
 *         - in: path
 *           Reference: PurchaseOrderId
 *           required: true
 *           description: PurchaseOrderId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: PurchaseOrder delete successfully
 *   
 */
router.route("/deletePurchaseOrderDetails/:PurchaseOrderId").delete(deletePurchaseOrderDetails)

/**
* @swagger
* /api/v1/updatePurchaseOrderDetails:
*   post:
*     summary: upConfirmationDate PurchaseOrder Details
*     tags: [PurchaseOrder]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/PurchaseOrder'
*     responses:
*       200:
*         description: upConfirmationDate PurchaseOrder Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/PurchaseOrder'
*       500:
*         description: Some server error
*/
router.route("/updatePurchaseOrderDetails").post(updatePurchaseOrderDetails)
module.exports = router

