const express = require("express")
const {CreatePurchaseEnquiryDetails,viewPurchaseEnquiryDetails,deletePurchaseEnquiryDetails,updatePurchaseEnquiryDetails,getSinglePurchaseEnquiryDetails} = require("../controller/PurchaseEnquiry_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     PurchaseEnquiry:
 *       type: object
 *       required:
 *         - PurchaseEnquiryId
 *         - Name
 *         - Email
 *         - Password
 *         - CompanyName
 *         - ContactNo
 *         - Country
 *         - SectorofActivity
 *         - EnquiryDetails
 *         - CreatedDate
 *         - GroupId
 *       properties:
 *         PurchaseEnquiryId:
 *           type: integer
 *           description: PurchaseEnquiryId
 *         Name:
 *           type: string
 *           description: Name
 *         CompanyName:
 *           type: string
 *           description: CompanyName
 *         Email:
 *           type: string
 *           description: PurchaseEnquiryId
 *         Password:
 *           type: string
 *           description: Password
 *         ContactNo:
 *           type: string
 *           description: PurchaseEnquiryId
 *         Country:
 *           type: string
 *           description: PurchaseEnquiryId
 *         SectorofActivity:
 *           type: string
 *           description: SectorofActivity
 *         EnquiryDetails:
 *           type: string
 *           description: EnquiryDetails
 *         CreatedDate:
 *           type: string
 *           description: EnquiryDetails
 *         GroupId:
 *           type: string
 *           description: EnquiryDetails
 *       example:
 *         PurchaseEnquiryId: autoGenerated
 *         Name: PurchaseEnquiry
 *         Email: PurchaseEnquiry@example.com
 *         Password:  PurchaseEnquiry@123
 *         CompanyName: PurchaseEnquiry
 *         ContactNo: CS-IT
 *         Country: India
 *         SectorofActivity: 01-03-2023
 *         EnquiryDetails: InActive
 *         CreatedDate: Active
 *         GroupId: GID103
 *         
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewPurchaseEnquiryDetails:
 *   get:
 *     summary: get all PurchaseEnquiry
 *     tags: [PurchaseEnquiry]
 *     responses:
 *       200:
 *         description: get All PurchaseEnquiry
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/PurchaseEnquiry'
 */
router.route("/viewPurchaseEnquiryDetails").get(viewPurchaseEnquiryDetails)


/**
 * @swagger
 * /api/v1/CreatePurchaseEnquiryDetails:
 *   post:
 *     summary: add a new PurchaseEnquiry
 *     tags: [PurchaseEnquiry]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/PurchaseEnquiry'
 *     responses:
 *       200:
 *         description: create PurchaseEnquiry successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/PurchaseEnquiry'
 *       500:
 *         description: Some server error
 */
 router.route("/CreatePurchaseEnquiryDetails").post(CreatePurchaseEnquiryDetails)

  /**
 * @swagger
 * /api/v1/deletePurchaseEnquiryDetails/{PurchaseEnquiryId}:
 *   delete:
 *     summary: Delete an PurchaseEnquiry
 *     tags: [PurchaseEnquiry]
 *     parameters:
 *         - in: path
 *           name: PurchaseEnquiryId
 *           required: true
 *           description: PurchaseEnquiryId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: PurchaseEnquiry delete successfully
 *   
 */
router.route("/deletePurchaseEnquiryDetails/:PurchaseEnquiryId").delete(deletePurchaseEnquiryDetails)

/**
* @swagger
* /api/v1/updatePurchaseEnquiryDetails:
*   post:
*     summary: upCompanyName PurchaseEnquiry Details
*     tags: [PurchaseEnquiry]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/PurchaseEnquiry'
*     responses:
*       200:
*         description: update PurchaseEnquiry Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/PurchaseEnquiry'
*       500:
*         description: Some server error
*/
router.route("/updatePurchaseEnquiryDetails").post(updatePurchaseEnquiryDetails)
/**
 * @swagger
 * /api/v1/getSinglePurchaseEnquiryDetails/{PurchaseEnquiryId}:
 *   get:
 *     summary: Get a PurchaseEnquiry by ID
 *     tags: [PurchaseEnquiry]
 *     description: Retrieve a PurchaseEnquiry by their unique ID.
 *     parameters:
 *       - in: path
 *         name: PurchaseEnquiryId
 *         required: true
 *         description: ID of the PurchaseEnquiry to retrieve
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Successfully retrieved the PurchaseEnquiry
 *       404:
 *         description: PurchaseEnquiry not found
 */
router.route("/getSinglePurchaseEnquiryDetails/:PurchaseEnquiryId").get(getSinglePurchaseEnquiryDetails)
module.exports = router

