const express = require("express")
const {CreatePurchaseSchedulingDetails,viewPurchaseSchedulingDetails,deletePurchaseSchedulingDetails,updatePurchaseSchedulingDetails} = require("../controller/PurchaseScheduling_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     PurchaseScheduling:
 *       type: object
 *       required:
 *         - PurchaseSchedulingId
 *         - CustomerId
 *         - Name
 *         - Date
 *         - Email
 *         - ContactNo
 *         - Description
 *         - CreatedDate
 *       properties:
 *         PurchaseSchedulingId:
 *           type: integer
 *           description: PurchaseSchedulingId
 *         Name:
 *           type: string
 *           description: Name
 *         Email:
 *           type: string
 *           description: Email
 *         Date:
 *           type: string
 *           description: PurchaseSchedulingId
 *         ContactNo:
 *           type: string
 *           description: ContactNo
 *         Description:
 *           type: string
 *           description: Description
 *         TotalAmount:
 *           type: string
 *           description: TotalAmount
 *         CustomerId:
 *           type: string
 *           description: TotalAmount
 *         CreatedDate:
 *           type: string
 *           description: TotalAmount
 *       example:
 *         PurchaseSchedulingId: autoGenerated
 *         Name: PurchaseScheduling
 *         CustomerId: CD101001
 *         Date: PurchaseScheduling@example.com
 *         Email: PurchaseScheduling@123
 *         Description: PurchaseScheduling bdhjbd
 *         CreatedDate: 07-11-2023
 *         ContactNo: 20237894561
 *       
 *         
 *        
 *
 */

/**
 * @swagger
 * /api/v1/viewPurchaseSchedulingDetails:
 *   get:
 *     summary: get all PurchaseScheduling
 *     tags: [PurchaseScheduling]
 *     responses:
 *       200:
 *         description: get All PurchaseScheduling
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/PurchaseScheduling'
 */
router.route("/viewPurchaseSchedulingDetails").get(viewPurchaseSchedulingDetails)


/**
 * @swagger
 * /api/v1/CreatePurchaseSchedulingDetails:
 *   post:
 *     summary: add a new PurchaseScheduling
 *     tags: [PurchaseScheduling]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/PurchaseScheduling'
 *     responses:
 *       200:
 *         description: create PurchaseScheduling successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/PurchaseScheduling'
 *       500:
 *         description: Some server error
 */
 router.route("/CreatePurchaseSchedulingDetails").post(CreatePurchaseSchedulingDetails)

  /**
 * @swagger
 * /api/v1/deletePurchaseSchedulingDetails/{PurchaseSchedulingId}:
 *   delete:
 *     summary: Delete a PurchaseScheduling
 *     tags: [PurchaseScheduling]
 *     parameters:
 *         - in: path
 *           name: PurchaseSchedulingId
 *           required: true
 *           description: PurchaseSchedulingId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: PurchaseScheduling deleted successfully
 */

router.route("/deletePurchaseSchedulingDetails/:PurchaseSchedulingId").delete(deletePurchaseSchedulingDetails)

/**
* @swagger
* /api/v1/updatePurchaseSchedulingDetails:
*   post:
*     summary: upEmail PurchaseScheduling Details
*     tags: [PurchaseScheduling]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/PurchaseScheduling'
*     responses:
*       200:
*         description: update PurchaseScheduling Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/PurchaseScheduling'
*       500:
*         description: Some server error
*/
router.route("/updatePurchaseSchedulingDetails").post(updatePurchaseSchedulingDetails)
module.exports = router

