const express = require("express")
const {CreateSalesQuotionDetails,viewSalesQuotionDetails,deleteSalesQuotionDetails,updateSalesQuotionDetails} = require("../controller/SalesQuotion_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     SalesQuotion:
 *       type: object
 *       required:
 *         - SalesQuotionId
 *         - Date
 *         - QuotionCurrency
 *         - CustomerName
 *         - CustomerId
 *         - CustomerAddress
 *         - Subject
 *         - ContactNumber
 *         - ContactEmail
 *         - ProductService
 *         - Description
 *         - Quantity
 *         - UnitPriceTHB
 *         - OfferValidity
 *         - PaymentTerm
 *         - Address
 *         - DeliveryTerm
 *         - DeliveryBasis
 *         - Status
 *       properties:
 *         SalesQuotionId :
 *           type: integer
 *           description: SalesQuotionId
 *         Date:
 *           type: string
 *           description: Date
 *         QuotionCurrency:
 *           type: string
 *           description: QuotionCurrency
 *         CustomerId:
 *           type: string
 *           description: CustomerId
 *         CustomerName:
 *           type: string
 *           description: CustomerName
 *         Subject:
 *           type: string
 *           description: Subject
 *         ContactNumber:
 *           type: string
 *           description: ContactNumber
 *         ContactEmail:
 *           type: string
 *           description:  ContactEmail
 *         ProductService:
 *           type: string
 *           description:  ProductService
 *         Description:
 *           type: string
 *           description:  Description
 *         Quantity:
 *           type: string
 *           description:  Quantity
 *         UnitPriceTHB:
 *           type: string
 *           description: UnitPriceTHB
 *         OfferValidity:
 *           type: string
 *           description: OfferValidity
 *         PaymentTerm:
 *           type: string
 *           description: PaymentTerm
 *         DeliveryTerm:
 *           type: string
 *           description: DeliveryTerm
 *         DeliveryBasis:
 *           type: string
 *           description: DeliveryBasis
 *         Status:
 *           type: string
 *           description: DeliveryBasis
 *       example:
 *         SalesQuotionId : autoGenerated
 *         QuotionCurrency : SalesQuotion
 *         CustomerName : Suger
 *         CustomerId : 503, KSL Tower 9th Floor, Sriayudhya Rd.,
 *         Subject : Bangkok
 *         ContactNumber : West
 *         Country: Domestic
 *         ContactEmail : West
 *         ProductService : Iron
 *         Description : Mr.Chiewchan
 *         Quantity : 0817441009
 *         UnitPriceTHB : 0817441009
 *         OfferValidity : 0817441009
 *         PaymentTerm : SalesQuotion@example.com
 *         DeliveryTerm : one-time-Structure
 *         DeliveryBasis : 08-03-2023
 *         Status : Pending
 */

/**
 * @swagger
 * /api/v1/viewSalesQuotionDetails:
 *   get:
 *     summary: get all SalesQuotion
 *     tags: [SalesQuotion]
 *     responses:
 *       200:
 *         description: get All SalesQuotion
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/SalesQuotion'
 */
router.route("/viewSalesQuotionDetails").get(viewSalesQuotionDetails)


/**
 * @swagger
 * /api/v1/CreateSalesQuotionDetails:
 *   post:
 *     summary: add a new SalesQuotion
 *     tags: [SalesQuotion]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/SalesQuotion'
 *     responses:
 *       200:
 *         description: create SalesQuotion successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/SalesQuotion'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateSalesQuotionDetails").post(CreateSalesQuotionDetails)

/**
 * @swagger
 * /api/v1/deleteSalesQuotionDetails/{SalesQuotionId}:
 *   delete:
 *     summary: Delete a SalesQuotion
 *     tags: [SalesQuotion]
 *     parameters:
 *       - in: path
 *         name: SalesQuotionId
 *         required: true
 *         description: SalesQuotionId is required
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: SalesQuotion deleted successfully
 */

router.route("/deleteSalesQuotionDetails/:SalesQuotionId").delete(deleteSalesQuotionDetails)

/**
* @swagger
* /api/v1/updateSalesQuotionDetails:
*   post:
*     summary: upAddress SalesQuotion Details
*     tags: [SalesQuotion]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/SalesQuotion'
*     responses:
*       200:
*         description: upAddress SalesQuotion Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/SalesQuotion'
*       500:
*         description: Some server error
*/
router.route("/updateSalesQuotionDetails").post(updateSalesQuotionDetails)
module.exports = router

