const express = require("express")
const {CreatesalesEnquiryitemdetailsDetails,viewsalesEnquiryitemdetailsDetails,deletesalesEnquiryitemdetailsDetails,updatesalesEnquiryitemdetailsDetails,getSinglesalesEnquiryitemdetailsDetails} = require("../controller/SalesEnquiryitemdetails_controller")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     salesEnquiryitemdetails:
 *       type: object
 *       required:
 *         - salesEnquiryitemdetailsId
 *         - SalesEnquiryId
 *         - ItemDetails
 *         - Description
 *         - Unit
 *         - Quantity
 *       properties:
 *         salesEnquiryitemdetailsId:
 *           type: integer
 *           description: salesEnquiryitemdetailsId
 *         SalesEnquiryId:
 *           type: string
 *           description: ItemDetails
 *         ItemDetails:
 *           type: string
 *           description: ItemDetails
 *         Description:
 *           type: string
 *           description: Description
 *         Unit:
 *           type: string
 *           description: Unit
 *         Quantity:
 *           type: string
 *           description: Quantity
 *       example:
 *         salesEnquiryitemdetailsId: autoGenerated
 *         SalesEnquiryId: item1 ,
 *         ItemDetails: item1 ,
 *         Description: njfbfbu ,
 *         Unit: 20 ,
 *         Quantity : 10 ,      
 *
 */

/**
 * @swagger
 * /api/v1/viewsalesEnquiryitemdetailsDetails:
 *   get:
 *     summary: get all salesEnquiryitemdetails
 *     tags: [salesEnquiryitemdetails]
 *     responses:
 *       200:
 *         description: get All salesEnquiryitemdetails
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/salesEnquiryitemdetails'
 */
router.route("/viewsalesEnquiryitemdetailsDetails").get(viewsalesEnquiryitemdetailsDetails)


/**
 * @swagger
 * /api/v1/CreatesalesEnquiryitemdetailsDetails:
 *   post:
 *     summary: add a new salesEnquiryitemdetails
 *     tags: [salesEnquiryitemdetails]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/salesEnquiryitemdetails'
 *     responses:
 *       200:
 *         description: create salesEnquiryitemdetails successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/salesEnquiryitemdetails'
 *       500:
 *         description: Some server error
 */
 router.route("/CreatesalesEnquiryitemdetailsDetails").post(CreatesalesEnquiryitemdetailsDetails)

  /**
 * @swagger
 * /api/v1/deletesalesEnquiryitemdetailsDetails/{salesEnquiryitemdetailsId}:
 *   delete:
 *     summary: Delete a salesEnquiryitemdetails
 *     tags: [salesEnquiryitemdetails]
 *     parameters:
 *         - in: path
 *           name: salesEnquiryitemdetailsId
 *           required: true
 *           description: salesEnquiryitemdetailsId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: salesEnquiryitemdetails deleted successfully
 */

router.route("/deletesalesEnquiryitemdetailsDetails/:salesEnquiryitemdetailsId").delete(deletesalesEnquiryitemdetailsDetails)

/**
* @swagger
* /api/v1/updatesalesEnquiryitemdetailsDetails:
*   post:
*     summary: upPassword salesEnquiryitemdetails Details
*     tags: [salesEnquiryitemdetails]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/salesEnquiryitemdetails'
*     responses:
*       200:
*         description: update salesEnquiryitemdetails Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/salesEnquiryitemdetails'
*       500:
*         description: Some server error
*/
router.route("/updatesalesEnquiryitemdetailsDetails").post(updatesalesEnquiryitemdetailsDetails)
/**
 * @swagger
 * /api/v1/getSinglesalesEnquiryitemdetailsDetails/{salesEnquiryitemdetailsId}:
 *   get:
 *     summary: Get a salesEnquiryitemdetails by ID
 *     tags: [salesEnquiryitemdetails]
 *     description: Retrieve a salesEnquiryitemdetails by their unique ID.
 *     parameters:
 *       - in: path
 *         name: salesEnquiryitemdetailsId
 *         required: true
 *         description: ID of the salesEnquiryitemdetails to retrieve
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Successfully retrieved the salesEnquiryitemdetails
 *       404:
 *         description: salesEnquiryitemdetails not found
 */
router.route("/getSinglesalesEnquiryitemdetailsDetails/:salesEnquiryitemdetailsId").get(getSinglesalesEnquiryitemdetailsDetails)
module.exports = router

