const express = require("express")
const {CreateSuplierDetails,viewSuplierDetails,deleteSuplierDetails,updateSuplierDetails,getSingleSuplierDetails} = require("../controller/SuplierController")
const router = express.Router()
/**
 * @swagger
 * components:
 *   schemas:
 *     Suplier:
 *       type: object
 *       required:
 *         - SuplierId
 *         - SuplierType
 *         - SuplierName
 *         - RegisteredOfficeAddress
 *         - RegisteredOfficeDistrict
 *         - RegisteredOfficeRegisteredOfficeCountry
 *         - RegisteredOfficeCountry
 *         - RegisteredOfficePin
 *         - BillingAddress
 *         - BillingDistrict
 *         - BillingAddressCountry
 *         - BillingAddressPin
 *         - ContactPersonName
 *         - Designation
 *         - Email
 *         - Address
 *         - LegelStructure
 *         - DateOfCompanyEstablish
 *         - TypeOfBussiness
 *         - GeograpicServiceArea
 *         - BankName
 *         - BankBranch
 *         - BankBranchCode
 *         - IFSCCode
 *         - BankManagerName
 *         - BankBranchAccountManagerName
 *         - BankAddress
 *         - BankEmailId
 *       properties:
 *         SuplierId :
 *           type: integer
 *           description: SuplierId
 *         SuplierType:
 *           type: string
 *           description: SuplierType
 *         SuplierName:
 *           type: string
 *           description: SuplierName
 *         RegisteredOfficeDistrict:
 *           type: string
 *           description: RegisteredOfficeDistrict
 *         RegisteredOfficeAddress:
 *           type: string
 *           description: RegisteredOfficeAddress
 *         RegisteredOfficeCountry:
 *           type: string
 *           description: RegisteredOfficeCountry
 *         RegisteredOfficePin:
 *           type: string
 *           description: RegisteredOfficePin
 *         BillingAddress:
 *           type: string
 *           description:  BillingAddress
 *         BillingDistrict:
 *           type: string
 *           description:  BillingDistrict
 *         BillingAddressCountry:
 *           type: string
 *           description:  BillingAddressCountry
 *         BillingAddressPin:
 *           type: string
 *           description:  BillingAddressPin
 *         ContactPersonName:
 *           type: string
 *           description: ContactPersonName
 *         Designation:
 *           type: string
 *           description: Designation
 *         Email:
 *           type: string
 *           description: Email
 *         LegelStructure:
 *           type: string
 *           description: LegelStructure
 *         DateOfCompanyEstablish:
 *           type: string
 *           description: DateOfCompanyEstablish
 *         TypeOfBussiness:
 *           type: string
 *           description: TypeOfBussiness
 *         GeograpicServiceArea:
 *           type: string
 *           description: GeograpicServiceArea
 *         BankName:
 *           type: string
 *           description: BankName
 *         BankBranch:
 *           type: string
 *           description: BankBranch
 *         IFSCCode:
 *           type: string
 *           description: IFSCCode
 *         BankManagerName:
 *           type: string
 *           description: BankManagerName
 *         BankBranchAccountManagerName:
 *           type: string
 *           description: BankBranchAccountManagerName
 *         BankAddress :
 *           type: string
 *           description: BankAddress
 *         BankEmailId:
 *           type: string
 *           description: BankEmailId
 *       example:
 *         SuplierId : autoGenerated
 *         SuplierName : Suplier
 *         RegisteredOfficeAddress : Suger
 *         RegisteredOfficeDistrict : 503, KSL Tower 9th Floor, Sriayudhya Rd.,
 *         RegisteredOfficeCountry : Bangkok
 *         RegisteredOfficePin : West
 *         Country: Domestic
 *         BillingAddress : West
 *         BillingDistrict : Iron
 *         BillingAddressCountry : Mr.Chiewchan
 *         BillingAddressPin : 0817441009
 *         ContactPersonName : 0817441009
 *         Designation : 0817441009
 *         Email : Suplier@example.com
 *         LegelStructure : one-time-Structure
 *         DateOfCompanyEstablish : 08-03-2023
 *         TypeOfBussiness : SuplierVehical
 *         GeograpicServiceArea : 8*14 
 *         BankName : AxisNo1
 *         BankBranchCode : AU10245
 *         IFSCCode : AXIS01245
 *         BankManagerName : Anish
 *         BankBranchAccountManagerName : Anksha
 *         BankAddress : bank
 *         BankEmailId :   bank@gmail.com
 *
 */

/**
 * @swagger
 * /api/v1/viewSuplierDetails:
 *   get:
 *     summary: get all Suplier
 *     tags: [Suplier]
 *     responses:
 *       200:
 *         description: get All Suplier
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               items:
 *                 $ref: '#/components/schemas/Suplier'
 */
router.route("/viewSuplierDetails").get(viewSuplierDetails)


/**
 * @swagger
 * /api/v1/CreateSuplierDetails:
 *   post:
 *     summary: add a new Suplier
 *     tags: [Suplier]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             $ref: '#/components/schemas/Suplier'
 *     responses:
 *       200:
 *         description: create Suplier successfull
 *         content:
 *           application/json:
 *             schema:
 *               $ref: '#/components/schemas/Suplier'
 *       500:
 *         description: Some server error
 */
 router.route("/CreateSuplierDetails").post(CreateSuplierDetails)

  /**
 * @swagger
 * /api/v1/deleteSuplierDetails/{SuplierId}:
 *   delete:
 *     summary: Delete an Suplier
 *     tags: [Suplier]
 *     parameters:
 *         - in: path
 *           SuplierName: SuplierId
 *           required: true
 *           description: SuplierId is required
 *           schema:
 *              type: string
 *     responses:
 *       200:
 *         description: Suplier delete successfully
 *   
 */
router.route("/deleteSuplierDetails/:SuplierId").delete(deleteSuplierDetails)

/**
* @swagger
* /api/v1/updateSuplierDetails:
*   post:
*     summary: upAddress Suplier Details
*     tags: [Suplier]
*     requestBody:
*       required: true
*       content:
*         application/json:
*           schema:
*             $ref: '#/components/schemas/Suplier'
*     responses:
*       200:
*         description: upAddress Suplier Details successfull
*         content:
*           application/json:
*             schema:
*               $ref: '#/components/schemas/Suplier'
*       500:
*         description: Some server error
*/
router.route("/updateSuplierDetails").post(updateSuplierDetails)
/**
 * @swagger
 * /api/v1/getSingleSuplierDetails/{SuplierId}:
 *   get:
 *     summary: Get a Suplier by ID
 *     tags: [Suplier]
 *     description: Retrieve a Suplier by their unique ID.
 *     parameters:
 *       - in: path
 *         name: SuplierId
 *         required: true
 *         description: ID of the Suplier to retrieve
 *         schema:
 *           type: string
 *     responses:
 *       200:
 *         description: Successfully retrieved the Suplier
 *       404:
 *         description: Suplier not found
 */
router.route("/getSingleSuplierDetails/:SuplierId").get(getSingleSuplierDetails)
module.exports = router

